# Generated by Django 2.2.5 on 2019-10-17 03:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('personalheight', models.IntegerField()),
                ('personalweight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateTimeField(auto_now_add=True)),
                ('originalEMG', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('temperature', models.FloatField()),
                ('spO2', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth.Person')),
            ],
        ),
    ]
