# Generated by Django 2.2.5 on 2019-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
