# Generated by Django 2.2.5 on 2019-10-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0005_auto_20191026_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='fati',
            field=models.IntegerField(null=True),
        ),
    ]
