# Generated by Django 2.2.5 on 2019-10-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_auto_20191026_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth.Person'),
        ),
    ]
